eureka:
    instance:
        hostname: localhost
    client: 
        registerWithEureka: false
        fetchRegistry: false
server:
    port: 1111
    enableSelfPreservation: false
management:
    security:
        enabled: false
spring:
    thymeleaf:
        enabled: false