spring:
    application:
        name: microservice-productoBackend
    freemaker:
        enabled: false
    thymeleaf:
        cache: false
        prefix: classpath:/templates
eureka:
    client: 
        serviceUrl:
            defaultZone: http://localhost:1111/eureka
        healthcheck:
           enable: true
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
server:
    port: 5555